### ISSUE TITLE
Bug: Code breaks after around 405 iterations

### ISSUE THREAD

**Issue by lguilhermers** [lguilhermers/stochastic_scenario_generator#3]
This issue has been reported in CEA.
Currently, it needs tests in other machines to verify if the problem is related to memory leak or something else.

**Comment by lguilhermers** [comment]
```
Simulation number 2402
Running archetypes-mapper with scenario = C:\CEA\CS2_Data_generator_plugin\test522
Using Daysim binaries from path: c:\users\luis.santos\documents\cityenergyanalyst\dependencies\daysim\bin64
Using Daysim data from path: c:\users\luis.santos\documents\cityenergyanalyst\dependencies\daysim\lib
verifying geometry files
zone: C:\CEA\CS2_Data_generator_plugin\test522\inputs\building-geometry\zone.shp
surroundings: C:\CEA\CS2_Data_generator_plugin\test522\inputs\building-geometry\surroundings.shp
Getting geometry materials
Creating 3D geometry and surfaces
Saving geometry pickle files in: C:\Users\LUIS~1.SAN\AppData\Local\Temp\tmpyj6fxs11\test522_radiation_geometry_pickle
Standardizing coordinate systems
Reading terrain geometry
Creating 3D building surfaces
Calculating terrain intersection of building geometries
Using single process
Calculation of terrain intersection for building 1 completed out of 1
Using single process
Calculation of terrain intersection for building 1 completed out of 8
Calculation of terrain intersection for building 2 completed out of 8
Calculation of terrain intersection for building 3 completed out of 8
Calculation of terrain intersection for building 4 completed out of 8
Calculation of terrain intersection for building 5 completed out of 8
Calculation of terrain intersection for building 6 completed out of 8
Calculation of terrain intersection for building 7 completed out of 8
Calculation of terrain intersection for building 8 completed out of 8
Generating geometry for surrounding buildings
Generating geometry for buildings in the zone of analysis
Using single process
Generating geometry for building 1 completed out of 1
Creating radiance material file
Creating radiance geometry file
Converting files for DAYSIM
Transforming weather files to daysim format
Running command `epw2wea "C:\CEA\CS2_Data_generator_plugin\test522\inputs\weather\weather.epw" "C:\Users\LUIS~1.SAN\AppData\Local\Temp\tmpyj6fxs11\cea_radiation\common_inputs\weather_60min.wea"`
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 131, in __apply_func_with_worker_stream
    result = func(*args)
  File "c:\users\luis.santos\documents\github\stochastic_scenario_generator\scenario_generator\stochastic_scenario_generator.py", line 166, in stochastic_scenario_generator
    radiation_main.main(config)  # runs solar radiation script
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 270, in main
    cea_daysim.execute_epw2wea(weather_file)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiance.py", line 122, in execute_epw2wea
    epw2wea_result = subprocess.run(shlex.split(command), stdout=subprocess.PIPE)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 8] Not enough memory resources are available to process this command
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 59, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 37, in script_runner
    script_module.main(config)
  File "c:\users\luis.santos\documents\github\stochastic_scenario_generator\scenario_generator\stochastic_scenario_generator.py", line 245, in main
    list_of_dataframe_with_instances)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 96, in wrapper
    result = map_result.get()
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
OSError: [WinError 8] Not enough memory resources are available to process this command
```
